kind: pipeline
name: build-and-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: download-rclone
    image: plugins/download
    settings: 
      source: https://github.com/rclone/rclone/releases/download/v1.48.0/rclone-v1.48.0-linux-amd64.zip
      destination: rclone.zip
      sha256: 2be0108485a90336dc6f521a39755f639cf64ab9f1b9b95cde7191d905c28f38
  - name: unzip
    image: alpine:3.10
    commands:
      - unzip -q -d . rclone.zip
      - mv rclone-v1.48.0-linux-amd64/rclone rclone
  - name: build-and-deploy-image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: garykim/rclone
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

---
kind: secret
name: docker_username
data: A8ASRPjhewpM7u/JoW99/Hn7py2QahTDtgfLSzZSMEV+QTU=

---
kind: secret
name: docker_password
data: r5buBDhofCeUdNVV9cuBczmcAPoeob19wZkmdvtVjxDQIrCFT/o5qSPSnphl6J6T7Q==
